#use jsd;
#create table stud(rno int primary key auto_increment,sname varchar(10),mark int)auto_increment=1001;
#insert into stud (sname,mark) values("riya",90);
#insert into stud (sname,mark) values('abhi',100),('arthi',79),('abinaya',100),('rasibro',98);
#delete from stud;
#insert into stud(sname,mark) values('abhi',100);
#truncate table stud;
#drop table stud;
#create table test(rno int primary key,accno int unique key,sname varchar(20));
#insert into test values(1001,3001,'rohini'),(1002,3002,'swathi'),(1003,3003,'harshni');
#select * from test;
#insert into test values(1004,null,'roshini');
#insert into test values(null,null,'roshini');
#create table sales(pno int primary key auto_increment,pname varchar(20),salesdate timestamp default current_timestamp);
#insert into sales(pname) values('apple_juice');
#select * from sales;
#insert into sales(pname) values('orange_juice');
#use jsd;
#create table testmark(sno int, sname varchar(25),mark int check(mark>=0 and mark<=100));
#insert into testmark values(1003,'priya',99),(1004,'shwetha',87),(1005,'harini',44);
#select * from testmark;
#delete from testmark where sname='riya';
#create table test2(sno int,sname varchar(20) not null,mark int);
#insert into test2 values(111,'janani',97);
#create table test1 (rno int primary key,sname varchar(20),mark int);
#insert into test1 values(111,'nira',null);
#select * from test1;
#create table testt2(rno int primary key,sname varchar(20),mark int,foreign key(rno) references test1(rno));
#insert into test1 values(112,'soni',86),(113,'janu',79),(114,'diya',83),(115,'latha',79);
select * from test1;
insert into test2 values(112,'dharu',87);
select * from test2;

